// Code generated by "stringer -type=BuiltinMethod,ExprKind -output context_string.go"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidMethod-0]
	_ = x[MethodIntToString-1]
	_ = x[MethodFloatToInt-2]
	_ = x[MethodByteArrayLength-3]
	_ = x[MethodByteArrayToString-4]
	_ = x[MethodStringLength-5]
	_ = x[MethodStringReverse-6]
	_ = x[MethodStringSubstring-7]
	_ = x[MethodStringToInt-8]
	_ = x[MethodEnumToInt-9]
	_ = x[MethodBoolToInt-10]
	_ = x[MethodArrayFirst-11]
	_ = x[MethodArrayLast-12]
	_ = x[MethodArraySize-13]
	_ = x[MethodArrayMin-14]
	_ = x[MethodArrayMax-15]
	_ = x[MethodStreamEOF-16]
	_ = x[MethodStreamSize-17]
	_ = x[MethodStreamPos-18]
}

const _BuiltinMethod_name = "InvalidMethodMethodIntToStringMethodFloatToIntMethodByteArrayLengthMethodByteArrayToStringMethodStringLengthMethodStringReverseMethodStringSubstringMethodStringToIntMethodEnumToIntMethodBoolToIntMethodArrayFirstMethodArrayLastMethodArraySizeMethodArrayMinMethodArrayMaxMethodStreamEOFMethodStreamSizeMethodStreamPos"

var _BuiltinMethod_index = [...]uint16{0, 13, 30, 46, 67, 90, 108, 127, 148, 165, 180, 195, 211, 226, 241, 255, 269, 284, 300, 315}

func (i BuiltinMethod) String() string {
	if i < 0 || i >= BuiltinMethod(len(_BuiltinMethod_index)-1) {
		return "BuiltinMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuiltinMethod_name[_BuiltinMethod_index[i]:_BuiltinMethod_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidKind-0]
	_ = x[RootKind-1]
	_ = x[StreamKind-2]
	_ = x[MethodKind-3]
	_ = x[StructParentKind-4]
	_ = x[StructRootKind-5]
	_ = x[IntegerKind-6]
	_ = x[FloatKind-7]
	_ = x[BooleanKind-8]
	_ = x[ArrayKind-9]
	_ = x[ByteArrayKind-10]
	_ = x[StringKind-11]
	_ = x[StructKind-12]
	_ = x[EnumKind-13]
	_ = x[EnumValueKind-14]
	_ = x[ParamKind-15]
	_ = x[AttrKind-16]
	_ = x[InstanceKind-17]
	_ = x[CastedValueKind-18]
}

const _ExprKind_name = "InvalidKindRootKindStreamKindMethodKindStructParentKindStructRootKindIntegerKindFloatKindBooleanKindArrayKindByteArrayKindStringKindStructKindEnumKindEnumValueKindParamKindAttrKindInstanceKindCastedValueKind"

var _ExprKind_index = [...]uint8{0, 11, 19, 29, 39, 55, 69, 80, 89, 100, 109, 122, 132, 142, 150, 163, 172, 180, 192, 207}

func (i ExprKind) String() string {
	if i < 0 || i >= ExprKind(len(_ExprKind_index)-1) {
		return "ExprKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExprKind_name[_ExprKind_index[i]:_ExprKind_index[i+1]]
}
