// Code generated by "stringer -type=Endianness"; DO NOT EDIT.

package kaitai

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnspecifiedOrder-0]
	_ = x[BigEndian-1]
	_ = x[LittleEndian-2]
}

const _Endianness_name = "UnspecifiedOrderBigEndianLittleEndian"

var _Endianness_index = [...]uint8{0, 16, 25, 37}

func (i Endianness) String() string {
	if i < 0 || i >= Endianness(len(_Endianness_index)-1) {
		return "Endianness(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Endianness_name[_Endianness_index[i]:_Endianness_index[i+1]]
}
