package golang

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

type goVar struct {
	name string
	typ  string
}

func (v goVar) String() string {
	return fmt.Sprintf("%s %s", v.name, v.typ)
}

type goVarList []goVar

func (v goVarList) String() string {
	vstrs := []string{}
	for _, n := range v {
		vstrs = append(vstrs, n.String())
	}
	return strings.Join(vstrs, ", ")
}

type goFields []goVar

func (v goFields) String() string {
	vstrs := []string{}
	for _, n := range v {
		vstrs = append(vstrs, n.String())
	}
	return strings.Join(vstrs, "\n\t")
}

type goStruct struct {
	name   string
	fields goFields
}

func (g *goStruct) emit(buf io.Writer) {
	_, _ = fmt.Fprintf(buf, "type %s struct {\n\t%s\n}\n\n", g.name, g.fields)
}

type goMethod struct {
	name string
	in   goVarList
	out  goVarList
}

func (g *goMethod) String() string {
	return fmt.Sprintf("%s(%s) (%s)\n", g.name, g.in, g.out)
}

type goMethods []goMethod

func (m goMethods) String() string {
	mstrs := []string{}
	for _, n := range m {
		mstrs = append(mstrs, n.String())
	}
	return strings.Join(mstrs, "\n\t")
}

type goInterface struct {
	name    string
	methods goMethods
}

func (g *goInterface) emit(buf io.Writer) {
	_, _ = fmt.Fprintf(buf, "type %s interface {\n\t%s\n}\n\n", g.name, g.methods)
}

type goFunc struct {
	recv   goVar
	name   string
	tmp    int
	in     goVarList
	out    goVarList
	source string
	pfx    string
}

func (g *goFunc) emit(buf io.Writer) {
	_, _ = fmt.Fprintf(buf, "func (%s) %s(%s) (%s) {\n%s}\n\n", g.recv.String(), g.name, g.in.String(), g.out.String(), g.source)
}

func (g *goFunc) preprintf(format string, args ...any) *goFunc {
	g.source = "\t" + g.pfx + fmt.Sprintf(format, args...) + "\n" + g.source
	return g
}

func (g *goFunc) printf(format string, args ...any) *goFunc {
	g.source += "\t" + g.pfx + fmt.Sprintf(format, args...) + "\n"
	return g
}

func (g *goFunc) indent() *goFunc {
	g.pfx += "\t"
	return g
}

func (g *goFunc) unindent() *goFunc {
	g.pfx = g.pfx[:len(g.pfx)-1]
	return g
}

type goEnumValue struct {
	name  string
	value int
}

type goEnum struct {
	name     string
	decltype string
	values   []goEnumValue
}

func (g *goEnum) emit(buf io.Writer) {
	_, _ = fmt.Fprintf(buf, "type %s %s\n", g.name, g.decltype)
	_, _ = fmt.Fprintf(buf, "const (\n")
	for _, v := range g.values {
		_, _ = fmt.Fprintf(buf, "\t%s %s = %d\n", v.name, g.name, v.value)
	}
	_, _ = fmt.Fprintf(buf, ")\n\n")
}

type goUnit struct {
	pkgname    string
	imports    map[string]string
	enums      []goEnum
	interfaces []goInterface
	structs    []goStruct
	methods    []goFunc
	vars       []string // package-level variable declarations
}

func (g *goUnit) emit(buf io.Writer) {
	_, _ = fmt.Fprint(buf, "// Generated by Zanbato. Do not edit!\n\n")
	_, _ = fmt.Fprintf(buf, "package %s\n\n", g.pkgname)
	if len(g.imports) > 0 {
		var keys []string
		for k := range g.imports {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		_, _ = fmt.Fprintf(buf, "import (\n")
		for _, k := range keys {
			_, _ = fmt.Fprintf(buf, "\t%s %q\n", g.imports[k], k)
		}
		_, _ = fmt.Fprintf(buf, ")\n\n")
	}
	for _, e := range g.enums {
		e.emit(buf)
	}
	for _, e := range g.interfaces {
		e.emit(buf)
	}
	for _, s := range g.structs {
		s.emit(buf)
	}
	for _, m := range g.methods {
		m.emit(buf)
	}
	for _, v := range g.vars {
		_, _ = fmt.Fprintln(buf, v)
		_, _ = fmt.Fprintln(buf)
	}
}
