package golang

import (
	"bytes"
	"fmt"
	"math/big"
	"strconv"
	"strings"

	"github.com/jchv/zanbato/kaitai"
	"github.com/jchv/zanbato/kaitai/expr"
	"github.com/jchv/zanbato/kaitai/kst"
	"github.com/jchv/zanbato/kaitai/types"
)

// KSTEmitter generates Go test files from KST specs.
type KSTEmitter struct {
	pkgName         string                    // package name for generated test (e.g. "spec")
	formatsPkg      string                    // import path/name for generated format code (e.g. "test_formats")
	srcDir          string                    // path prefix for binary test data files
	ResolvedStructs map[string]*kaitai.Struct // meta.id -> resolved struct (for cross-file lookups)
}

// NewKSTEmitter creates a KST test emitter.
func NewKSTEmitter(pkgName, formatsPkg, srcDir string) *KSTEmitter {
	return &KSTEmitter{
		pkgName:    pkgName,
		formatsPkg: formatsPkg,
		srcDir:     srcDir,
	}
}

// Emit generates a Go test file from a KST spec and its corresponding KSY struct.
func (e *KSTEmitter) Emit(spec *kst.TestSpec, ks *kaitai.Struct) (string, []byte) {
	g := &kstGen{
		emitter:    e,
		spec:       spec,
		rootStruct: ks,
		tmpCounter: 0,
		imports: map[string]string{
			"os":            "",
			"testing":       "",
			"runtime/debug": "",
			"github.com/jchw-forks/kaitai_struct_go_runtime/kaitai": "",
		},
	}
	body := g.generate()
	return kstFileName(spec.ID), body
}

func kstFileName(id string) string {
	return id + "_test.go"
}

// kstGen holds state for generating a single test file.
type kstGen struct {
	emitter     *KSTEmitter
	spec        *kst.TestSpec
	rootStruct  *kaitai.Struct
	tmpCounter  int
	imports     map[string]string
	buf         bytes.Buffer
	indent      int
	needAssert  bool
	needReflect bool
}

func (g *kstGen) generate() []byte {
	className := ksToGoName(g.spec.ID)

	// Generate test body first so we know which imports are needed
	var body bytes.Buffer
	g.buf = body

	g.writeln("func Test%s(t *testing.T) {", className)
	g.indent++
	g.writeln("defer func() {")
	g.indent++
	g.writeln("if r := recover(); r != nil {")
	g.indent++
	g.writeln("debug.PrintStack()")
	g.writeln("t.Fatal(\"unexpected panic:\", r)")
	g.indent--
	g.writeln("}")
	g.indent--
	g.writeln("}()")
	g.writeln("f, err := os.Open(\"%s%s\")", g.emitter.srcDir, g.spec.Data)
	g.writeln("if err != nil {")
	g.indent++
	g.writeln("t.Fatal(err)")
	g.indent--
	g.writeln("}")
	g.writeln("s := kaitai.NewStream(f)")
	g.writeln("var r %s", className)

	if g.spec.Exception != nil {
		g.emitParseExpectError(g.spec.Exception)
	} else {
		g.writeln("err = r.Read(s, &r, &r)")
		if g.rootStruct.Meta.Debug {
			// Debug mode: ignore Read errors - partial parsing is expected
			g.writeln("_ = err")
		} else {
			g.writeln("if err != nil {")
			g.indent++
			g.writeln("t.Fatal(err)")
			g.indent--
			g.writeln("}")
		}
		g.writeln("")
		g.emitAsserts()
	}

	g.indent--
	g.writeln("}")
	g.writeln("")

	// Generate roundtrip (write) test for non-exception specs that do full reads
	if g.spec.Exception == nil && !g.rootStruct.Meta.Debug {
		g.emitRoundtripTest(className)
	}

	bodyBytes := g.buf.Bytes()

	// Now assemble the full file with imports
	if g.needAssert {
		g.imports["github.com/stretchr/testify/assert"] = ""
	}
	if g.needReflect {
		g.imports["reflect"] = ""
	}

	var out bytes.Buffer
	out.WriteString("// Autogenerated from KST by Zanbato: please remove this line if doing any edits by hand!\n\n")
	fmt.Fprintf(&out, "package %s\n\n", g.emitter.pkgName)
	out.WriteString("import (\n")
	for pkg, alias := range g.imports {
		if alias != "" {
			fmt.Fprintf(&out, "\t%s %q\n", alias, pkg)
		} else {
			fmt.Fprintf(&out, "\t%q\n", pkg)
		}
	}
	if g.emitter.formatsPkg != "" {
		fmt.Fprintf(&out, "\t. %q\n", g.emitter.formatsPkg)
	}
	out.WriteString(")\n\n")
	out.Write(bodyBytes)

	return out.Bytes()
}

func (g *kstGen) emitParseExpectError(exc *kst.ExpectedException) {
	g.needAssert = true
	g.writeln("err = r.Read(s, &r, &r)")
	g.writeln("assert.Error(t, err)")

	errType := kstExceptionToGoType(exc.Type)
	if errType == "io.ErrUnexpectedEOF" {
		g.imports["io"] = ""
		g.writeln("assert.True(t, errors.Is(err, io.ErrUnexpectedEOF) || errors.Is(err, io.EOF), \"expected EOF error, got: %%v\", err)")
		g.imports["errors"] = ""
	} else {
		g.writeln("var wantErr %s", errType)
		g.writeln("assert.ErrorAs(t, err, &wantErr)")
	}
}

func (g *kstGen) emitRoundtripTest(className string) {
	g.imports["bytes"] = ""
	g.imports["os"] = ""

	g.writeln("func Test%s_Roundtrip(t *testing.T) {", className)
	g.indent++
	g.writeln("defer func() {")
	g.indent++
	g.writeln("if r := recover(); r != nil {")
	g.indent++
	g.writeln("debug.PrintStack()")
	g.writeln("t.Fatal(\"unexpected panic:\", r)")
	g.indent--
	g.writeln("}")
	g.indent--
	g.writeln("}()")

	// Read original data
	g.writeln("origData, err := os.ReadFile(\"%s%s\")", g.emitter.srcDir, g.spec.Data)
	g.writeln("if err != nil {")
	g.indent++
	g.writeln("t.Fatal(err)")
	g.indent--
	g.writeln("}")

	// Parse and note how much was consumed
	g.writeln("s := kaitai.NewStream(bytes.NewReader(origData))")
	g.writeln("var r %s", className)
	g.writeln("if err := r.Read(s, &r, &r); err != nil {")
	g.indent++
	g.writeln("t.Fatal(err)")
	g.indent--
	g.writeln("}")
	g.writeln("readPos, _ := s.Pos()")

	// Write to a growable buffer
	g.writeln("buf := kaitai.NewSeekableBuffer(nil)")
	g.writeln("ws := kaitai.NewWriter(buf)")
	g.writeln("if err := r.Write(ws); err != nil {")
	g.indent++
	g.writeln("t.Fatal(\"write error:\", err)")
	g.indent--
	g.writeln("}")

	// Compare: only compare up to what was read (some formats don't consume entire file)
	g.needAssert = true
	g.writeln("written := buf.Bytes()")
	g.writeln("expected := origData[:readPos]")
	g.writeln("if len(expected) == 0 && len(written) == 0 { return }")
	g.writeln("assert.Equal(t, expected, written, \"roundtrip mismatch\")")

	g.indent--
	g.writeln("}")
	g.writeln("")
}

func (g *kstGen) emitAsserts() {
	for _, a := range g.spec.Asserts {
		switch a := a.(type) {
		case kst.TestEquals:
			g.emitTestEquals(a)
		case kst.TestException:
			g.emitTestException(a)
		}
	}
}

func (g *kstGen) emitTestEquals(check kst.TestEquals) {
	g.needAssert = true

	// Check for null assertion
	if check.Expected == "null" {
		g.emitNullAssert(check.Actual)
		return
	}

	// Parse the expected expression to determine its type
	expectedExpr, err := expr.ParseExpr(check.Expected)
	if err != nil {
		g.writeln("t.Fatalf(\"could not parse expected expression: %s\")", check.Expected)
		return
	}

	// Check if expected is a float (needs InDelta comparison)
	if isFloatExpected(expectedExpr.Root) {
		g.emitFloatEquality(check, expectedExpr)
		return
	}

	// Check if expected is an array literal
	if arr, ok := expectedExpr.Root.(expr.ArrayNode); ok {
		g.emitArrayEquality(check, arr)
		return
	}

	// Standard equality assertion
	actualCode := g.translateActual(check.Actual)
	expectedCode := g.translateExpected(expectedExpr.Root)
	g.writeln("assert.EqualValues(t, %s, %s)", expectedCode, actualCode)
}

func (g *kstGen) emitNullAssert(actual string) {
	g.needAssert = true
	actualCode := g.translateActual(actual)
	g.writeln("assert.Nil(t, %s)", actualCode)
}

func (g *kstGen) emitFloatEquality(check kst.TestEquals, expectedExpr *expr.Expr) {
	actualCode := g.translateActual(check.Actual)
	expectedCode := g.translateExpected(expectedExpr.Root)
	g.writeln("assert.InDelta(t, %s, %s, 1e-6)", expectedCode, actualCode)
}

func (g *kstGen) emitArrayEquality(check kst.TestEquals, arr expr.ArrayNode) {
	actualCode := g.translateActual(check.Actual)

	// Check if all elements are byte-range integers (0-255 with no expressions) -> []uint8
	if isByteArray(arr) {
		g.writeln("assert.EqualValues(t, %s, %s)", g.translateExpectedByteArray(arr), actualCode)
		return
	}

	// For non-byte arrays, use element-wise comparison to avoid type mismatches
	// (e.g. []int vs []uint8, []int vs []int32)
	g.needReflect = true
	g.writeln("{")
	g.indent++
	g.writeln("actual := %s", actualCode)
	g.writeln("av := reflect.ValueOf(actual)")
	g.writeln("assert.EqualValues(t, %d, av.Len())", len(arr.Items))
	for i, item := range arr.Items {
		g.writeln("assert.EqualValues(t, %s, av.Index(%d).Interface())", g.translateExpected(item), i)
	}
	g.indent--
	g.writeln("}")
}

func (g *kstGen) emitTestException(check kst.TestException) {
	g.needAssert = true

	// Parse the actual expression to determine if it's an instance call.
	// Per-assertion exceptions test that evaluating the expression produces an error.
	parsed, err := expr.ParseExpr(check.Actual)
	if err != nil {
		g.writeln("t.Fatalf(\"could not parse actual expression: %s\")", check.Actual)
		return
	}

	// The actual expression should be an identifier (instance name).
	// Generate a call that captures the error instead of fatal-ing.
	switch n := parsed.Root.(type) {
	case expr.IdentNode:
		goName := ksToGoName(n.Identifier)
		g.writeln("_, err = r.%s()", goName)
	case expr.MemberNode:
		// Build the access chain, but the final call should capture err
		operandCode := g.translateActualNode(n.Operand, g.rootStruct, "r")
		goName := ksToGoName(n.Property)
		if isInstanceOf(g.resolveFieldStruct(n.Operand, g.rootStruct), n.Property) || g.isInstanceAnywhere(n.Property) {
			g.writeln("_, err = %s.%s()", operandCode, goName)
		} else {
			// Not an instance - shouldn't normally happen for exception asserts
			g.writeln("_ = %s.%s", operandCode, goName)
			g.writeln("t.Fatal(\"expected exception but expression is not an instance call\")")
			return
		}
	default:
		g.writeln("t.Fatalf(\"unsupported exception assert expression type: %T\")", check.Actual)
		return
	}

	g.writeln("assert.Error(t, err)")
}

// translateActual translates a KS "actual" expression (e.g. "opcodes[0].code")
// into Go test code (e.g. "r.Opcodes[0].Code"). When the expression involves
// an instance access, generates tmp/err handling and returns the tmp variable name.
func (g *kstGen) translateActual(actualExpr string) string {
	parsed, err := expr.ParseExpr(actualExpr)
	if err != nil {
		// Emit a t.Fatal so the test fails visibly rather than silently passing.
		g.writeln("t.Fatalf(\"could not parse actual expression: %s\")", actualExpr)
		return "nil"
	}

	return g.translateActualNode(parsed.Root, g.rootStruct, "r")
}

// translateActualNode recursively translates an actual expression AST node.
// ks is the struct context for looking up fields, prefix is the Go expression so far.
func (g *kstGen) translateActualNode(node expr.Node, ks *kaitai.Struct, prefix string) string {
	switch n := node.(type) {
	case expr.IdentNode:
		return g.translateFieldAccess(n.Identifier, ks, prefix)

	case expr.MemberNode:
		// First translate the operand
		operandCode := g.translateActualNode(n.Operand, ks, prefix)

		// Handle intrinsic properties that are ALWAYS intrinsics (never field names)
		switch n.Property {
		case "size", "length":
			// For streams (_io), call the Size() method instead of len()
			if member, ok := n.Operand.(expr.MemberNode); ok && member.Property == "_io" {
				return fmt.Sprintf("(func() int64 { v, _ := %s.Size(); return v }())", operandCode)
			}
			return fmt.Sprintf("len(%s)", operandCode)
		case "to_s":
			g.imports["strconv"] = ""
			return fmt.Sprintf("strconv.FormatInt(int64(%s), 10)", operandCode)
		case "to_i":
			return fmt.Sprintf("int(%s)", operandCode)
		case "_parent":
			return fmt.Sprintf("%s.Parent_", operandCode)
		case "_root":
			return fmt.Sprintf("%s.Root_", operandCode)
		case "_io":
			return fmt.Sprintf("%s.IO_", operandCode)
		}

		// Resolve the type of the operand to look up the member field
		childStruct := g.resolveFieldStruct(n.Operand, ks)

		// If the operand is a switch-typed field, we need a type assertion
		// to access its members since it's any-typed in Go
		if childStruct != nil && g.isSwitchTypedField(n.Operand, ks) {
			goType := g.goTypeNameForStruct(childStruct)
			operandCode = fmt.Sprintf("%s.(*%s)", operandCode, goType)
		}

		// For properties that could be field names or intrinsics (first, last),
		// check if the operand resolves to a struct with that field first
		if childStruct != nil {
			return g.translateFieldAccess(n.Property, childStruct, operandCode)
		}

		// Fallback intrinsics
		switch n.Property {
		case "first":
			return fmt.Sprintf("%s[0]", operandCode)
		case "last":
			return fmt.Sprintf("%s[len(%s)-1]", operandCode, operandCode)
		}

		return g.translateFieldAccess(n.Property, nil, operandCode)

	case expr.SubscriptNode:
		arrCode := g.translateActualNode(n.A, ks, prefix)
		idxCode := g.translateExpected(n.B)
		return fmt.Sprintf("%s[%s]", arrCode, idxCode)

	case expr.CastNode:
		// .as<type> - translate to Go type assertion
		operandCode := g.translateActualNode(n.Operand, ks, prefix)
		goType := g.kstCastTypeToGo(n.TypeName)
		isPrimitive := goType == "[]byte" || goType == "string" ||
			goType == "uint8" || goType == "uint16" || goType == "uint32" || goType == "uint64" ||
			goType == "int8" || goType == "int16" || goType == "int32" || goType == "int64" ||
			goType == "float32" || goType == "float64"
		// Check if the operand is already a concrete type (not any-typed).
		// If so, a type assertion is invalid - just return the operand or cast it.
		if isPrimitive {
			// Check if the operand field is any-typed (switch field, conditional, etc.)
			// If not, the assertion is a no-op - just return the operand
			operandIsAny := false
			if ident, ok := n.Operand.(expr.IdentNode); ok {
				operandIsAny = g.isSwitchTypedField(n.Operand, ks) || g.isConditionalField(ident.Identifier, ks)
			} else if member, ok := n.Operand.(expr.MemberNode); ok {
				parentStruct := g.resolveFieldStruct(member.Operand, ks)
				if parentStruct != nil {
					operandIsAny = g.isSwitchTypedField(expr.IdentNode{Identifier: member.Property}, parentStruct) ||
						g.isConditionalField(member.Property, parentStruct)
				}
			}
			if operandIsAny {
				return fmt.Sprintf("%s.(%s)", operandCode, goType)
			}
			return operandCode // already the correct type
		}
		return fmt.Sprintf("%s.(*%s)", operandCode, goType)

	default:
		g.writeln("t.Fatalf(\"unsupported actual expression node: %T\")", node)
		return "nil"
	}
}

// translateFieldAccess generates Go code for accessing a field on a struct.
// If the field is an instance, it generates tmp/err handling.
func (g *kstGen) translateFieldAccess(fieldName string, ks *kaitai.Struct, prefix string) string {
	goName := ksToGoName(fieldName)

	// Check if it's an instance - first in the resolved struct, then globally
	if isInstanceOf(ks, fieldName) || (ks == nil && g.isInstanceAnywhere(fieldName)) {
		g.tmpCounter++
		tmpVar := fmt.Sprintf("tmp%d", g.tmpCounter)
		g.writeln("%s, err := %s.%s()", tmpVar, prefix, goName)
		g.writeln("if err != nil {")
		g.indent++
		g.writeln("t.Fatal(err)")
		g.indent--
		g.writeln("}")
		return tmpVar
	}

	return fmt.Sprintf("%s.%s", prefix, goName)
}

// isInstanceAnywhere checks if a field name is an instance in any struct definition.
func (g *kstGen) isInstanceAnywhere(fieldName string) bool {
	return g.searchInstances(g.rootStruct, fieldName)
}

func (g *kstGen) searchInstances(ks *kaitai.Struct, fieldName string) bool {
	if ks == nil {
		return false
	}
	if isInstanceOf(ks, fieldName) {
		return true
	}
	for _, sub := range ks.Structs {
		if g.searchInstances(sub, fieldName) {
			return true
		}
	}
	return false
}

// resolveFieldStruct resolves the KS struct type for a field accessed via an expression.
// Returns nil if the type can't be resolved (we fall back to direct field access).
func (g *kstGen) resolveFieldStruct(node expr.Node, contextStruct *kaitai.Struct) *kaitai.Struct {
	if contextStruct == nil {
		return nil
	}

	switch n := node.(type) {
	case expr.IdentNode:
		return g.findFieldTypeStruct(contextStruct, n.Identifier)

	case expr.SubscriptNode:
		// Array subscript doesn't change the element type
		return g.resolveFieldStruct(n.A, contextStruct)

	case expr.CastNode:
		// .as<type> - resolve the target type
		return g.findStructByName(contextStruct, n.TypeName)

	case expr.MemberNode:
		parentStruct := g.resolveFieldStruct(n.Operand, contextStruct)
		if parentStruct == nil {
			return nil
		}
		return g.findFieldTypeStruct(parentStruct, n.Property)
	}

	return nil
}

// findFieldTypeStruct looks up a field in a struct and resolves its user type.
func (g *kstGen) findFieldTypeStruct(ks *kaitai.Struct, fieldName string) *kaitai.Struct {
	// Search seq and instances for the field
	var attr *kaitai.Attr
	for _, a := range ks.Seq {
		if string(a.ID) == fieldName {
			attr = a
			break
		}
	}
	if attr == nil {
		for _, a := range ks.Instances {
			if string(a.ID) == fieldName {
				attr = a
				break
			}
		}
	}
	if attr == nil {
		return nil
	}

	// Resolve the user type
	if attr.Type.TypeRef != nil && attr.Type.TypeRef.Kind == types.User {
		return g.findStructByName(ks, attr.Type.TypeRef.User.Name)
	}

	// For switch-typed fields, try to resolve if there's only one concrete type
	// (e.g., default-only switch, or all cases map to the same type)
	if attr.Type.TypeSwitch != nil {
		var singleType string
		for key, caseType := range attr.Type.TypeSwitch.Cases {
			_ = key
			if caseType.Kind == types.User {
				if singleType == "" {
					singleType = caseType.User.Name
				} else if singleType != caseType.User.Name {
					singleType = ""
					break
				}
			} else {
				singleType = ""
				break
			}
		}
		if singleType != "" {
			return g.findStructByName(ks, singleType)
		}
	}

	return nil
}

// isSwitchTypedField checks if a node resolves to a switch-typed field (any in Go).
// It checks both seq fields and instances in the given struct.
func (g *kstGen) isSwitchTypedField(node expr.Node, ks *kaitai.Struct) bool {
	if ks == nil {
		return false
	}
	var fieldName string
	switch n := node.(type) {
	case expr.IdentNode:
		fieldName = n.Identifier
	case expr.MemberNode:
		// For chained access like tags[0].tag_content, resolve through context
		parentStruct := g.resolveFieldStruct(n.Operand, ks)
		if parentStruct != nil {
			return g.isSwitchTypedField(expr.IdentNode{Identifier: n.Property}, parentStruct)
		}
		return false
	case expr.SubscriptNode:
		return g.isSwitchTypedField(n.A, ks)
	default:
		return false
	}
	for _, a := range ks.Seq {
		if string(a.ID) == fieldName {
			return a.Type.TypeSwitch != nil
		}
	}
	for _, a := range ks.Instances {
		if string(a.ID) == fieldName {
			return a.Type.TypeSwitch != nil
		}
	}
	return false
}

// isConditionalField checks if a field has an if: condition (making it any-typed in Go).
func (g *kstGen) isConditionalField(fieldName string, ks *kaitai.Struct) bool {
	if ks == nil {
		return false
	}
	for _, a := range ks.Seq {
		if string(a.ID) == fieldName {
			return a.If != nil
		}
	}
	for _, a := range ks.Instances {
		if string(a.ID) == fieldName {
			return a.If != nil
		}
	}
	return false
}

// findStructByName finds a nested struct by its KS name (handling :: separators).
func (g *kstGen) findStructByName(context *kaitai.Struct, name string) *kaitai.Struct {
	// Handle :: scope separators (e.g. "switch_manual_int_size::chunk::chunk_meta")
	parts := strings.Split(name, "::")

	current := context
	for i, part := range parts {
		found := false
		// First check if it refers to the root type itself
		if current != nil && string(current.ID) == part {
			found = true
			continue
		}
		// Search nested structs
		if current != nil {
			for _, sub := range current.Structs {
				if string(sub.ID) == part {
					current = sub
					found = true
					break
				}
			}
		}
		// If not found as a child, search from the root level
		// (Kaitai types can reference siblings, not just children)
		if !found && g.rootStruct != nil && g.rootStruct != current {
			for _, sub := range g.rootStruct.Structs {
				if string(sub.ID) == part {
					current = sub
					found = true
					break
				}
			}
		}
		// Search resolved imports (cross-file types)
		if !found && i == 0 && g.emitter.ResolvedStructs != nil {
			if resolved, ok := g.emitter.ResolvedStructs[part]; ok {
				current = resolved
				found = true
			}
		}
		if !found {
			return nil
		}
	}
	return current
}

// translateExpected translates a KS expected-value expression to Go code.
func (g *kstGen) translateExpected(node expr.Node) string {
	switch n := node.(type) {
	case expr.IntNode:
		v := n.Integer
		if v.IsInt64() {
			i := v.Int64()
			if i < 0 {
				return fmt.Sprintf("%d", i)
			}
			// Use hex for large values
			if i > 0xFFFF {
				return fmt.Sprintf("0x%X", i)
			}
			return fmt.Sprintf("%d", i)
		}
		if v.IsUint64() {
			u := v.Uint64()
			return fmt.Sprintf("uint64(%d)", u)
		}
		return v.String()

	case expr.StringNode:
		return strconv.Quote(n.Str)

	case expr.BoolNode:
		if n.Bool {
			return "true"
		}
		return "false"

	case expr.FloatNode:
		f, _ := n.Float.Float64()
		return strconv.FormatFloat(f, 'E', -1, 64)

	case expr.ArrayNode:
		// Byte arrays get translated to []uint8{...}
		if isByteArray(n) {
			return g.translateExpectedByteArray(n)
		}
		// For generic arrays, translate individual elements
		parts := make([]string, len(n.Items))
		for i, item := range n.Items {
			parts[i] = g.translateExpected(item)
		}
		return "[]any{" + strings.Join(parts, ", ") + "}"

	case expr.ScopeNode:
		// Handle enum constants like enum_0::animal::cat
		return g.translateEnumScope(n)

	case expr.CastNode:
		// Handle .as<type> - e.g. [].as<bytes> -> []uint8{} or 0.5.as<f4> -> float32(0.5)
		if n.TypeName == "bytes" {
			return g.translateExpected(n.Operand)
		}
		if n.TypeName == "f4" || n.TypeName == "f8" {
			inner := g.translateExpected(n.Operand)
			if n.TypeName == "f4" {
				return fmt.Sprintf("float32(%s)", inner)
			}
			return fmt.Sprintf("float64(%s)", inner)
		}
		return g.translateExpected(n.Operand)

	case expr.UnaryNode:
		switch n.Op {
		case expr.OpNegate:
			// Special case: -BigInt that fits in int64 (e.g. math.MinInt64)
			if intNode, ok := n.Operand.(expr.IntNode); ok {
				negated := new(big.Int).Neg(intNode.Integer)
				if negated.IsInt64() {
					i := negated.Int64()
					if i < -0xFFFF {
						// Use the original (positive) big.Int for formatting
						// to avoid int64 overflow on MinInt64
						return fmt.Sprintf("-0x%X", intNode.Integer)
					}
					return fmt.Sprintf("%d", i)
				}
			}
			return "-" + g.translateExpected(n.Operand)
		case expr.OpInvert:
			return "^" + g.translateExpected(n.Operand)
		}
		return "!" + g.translateExpected(n.Operand)

	case expr.BinaryNode:
		a := g.translateExpected(n.A)
		b := g.translateExpected(n.B)
		switch n.Op {
		case expr.OpAdd:
			return fmt.Sprintf("(%s + %s)", a, b)
		case expr.OpSub:
			return fmt.Sprintf("(%s - %s)", a, b)
		case expr.OpMult:
			return fmt.Sprintf("(%s * %s)", a, b)
		case expr.OpDiv:
			return fmt.Sprintf("(%s / %s)", a, b)
		case expr.OpMod:
			return fmt.Sprintf("(%s %% %s)", a, b)
		default:
			g.writeln("t.Fatalf(\"unsupported expected binary operator: %s\")", n.Op)
			return "nil"
		}

	default:
		g.writeln("t.Fatalf(\"unsupported expected expression node: %T\")", node)
		return "nil"
	}
}

func (g *kstGen) translateExpectedByteArray(arr expr.ArrayNode) string {
	parts := make([]string, len(arr.Items))
	for i, item := range arr.Items {
		parts[i] = g.translateExpected(item)
	}
	return "[]uint8{" + strings.Join(parts, ", ") + "}"
}

// translateEnumScope translates a KS enum scope (e.g. enum_0::animal::cat) to a Go constant.
func (g *kstGen) translateEnumScope(node expr.ScopeNode) string {
	// Build the full scope path
	var parts []string
	var current expr.Node = node
	for {
		if sn, ok := current.(expr.ScopeNode); ok {
			parts = append([]string{sn.Type}, parts...)
			current = sn.Operand
		} else if in, ok := current.(expr.IdentNode); ok {
			parts = append([]string{in.Identifier}, parts...)
			break
		} else {
			break
		}
	}

	// Convert to Go constant name: TypeName_EnumName__ValueName
	if len(parts) >= 3 {
		var goName strings.Builder
		goName.WriteString(ksToGoName(parts[0]))
		for _, part := range parts[1 : len(parts)-1] {
			goName.WriteString("_" + ksToGoName(part))
		}
		goName.WriteString("__" + ksToGoName(parts[len(parts)-1]))
		return goName.String()
	}

	// Fallback
	goNames := make([]string, len(parts))
	for i, p := range parts {
		goNames[i] = ksToGoName(p)
	}
	return strings.Join(goNames, "_")
}

// kstCastTypeToGo converts a KS type name from .as<type> to a Go type name.
// The KST scope path (e.g. "root::chunk::chunk_body::chunk_meta") may differ
// from the actual struct nesting in the KSY. We resolve through the KSY hierarchy
// and build the Go name from the actual struct definition position.
func (g *kstGen) kstCastTypeToGo(typeName string) string {
	if typeName == "bytes" {
		return "[]byte"
	}
	// Handle primitive KS type casts
	switch typeName {
	case "u1":
		return "uint8"
	case "u2", "u2le", "u2be":
		return "uint16"
	case "u4", "u4le", "u4be":
		return "uint32"
	case "u8", "u8le", "u8be":
		return "uint64"
	case "s1":
		return "int8"
	case "s2", "s2le", "s2be":
		return "int16"
	case "s4", "s4le", "s4be":
		return "int32"
	case "s8", "s8le", "s8be":
		return "int64"
	case "f4", "f4le", "f4be":
		return "float32"
	case "f8", "f8le", "f8be":
		return "float64"
	case "str", "strz":
		return "string"
	}
	// Try to resolve through the struct hierarchy to get the actual Go type name
	target := g.findStructByName(g.rootStruct, typeName)
	if target != nil {
		return g.goTypeNameForStruct(target)
	}
	// Fallback: naive joining (won't always be correct but better than nothing)
	parts := strings.Split(typeName, "::")
	goNames := make([]string, len(parts))
	for i, p := range parts {
		goNames[i] = ksToGoName(p)
	}
	return strings.Join(goNames, "_")
}

// goTypeNameForStruct builds the Go type name for a struct by finding its
// position in the root struct's type hierarchy.
func (g *kstGen) goTypeNameForStruct(target *kaitai.Struct) string {
	var path []string
	if g.buildStructPath(g.rootStruct, target, &path) {
		return strings.Join(path, "_")
	}
	// Shouldn't happen if target was found via findStructByName
	return ksToGoName(string(target.ID))
}

func (g *kstGen) buildStructPath(current *kaitai.Struct, target *kaitai.Struct, path *[]string) bool {
	*path = append(*path, ksToGoName(string(current.ID)))
	if current == target {
		return true
	}
	for _, sub := range current.Structs {
		if g.buildStructPath(sub, target, path) {
			return true
		}
	}
	*path = (*path)[:len(*path)-1]
	return false
}

func (g *kstGen) writeln(format string, args ...any) {
	var line string
	if len(args) > 0 {
		line = fmt.Sprintf(format, args...)
	} else {
		line = format
	}
	for range g.indent {
		g.buf.WriteByte('\t')
	}
	g.buf.WriteString(line)
	g.buf.WriteByte('\n')
}

// isInstanceOf checks if a field name is an instance on a specific struct.
func isInstanceOf(ks *kaitai.Struct, fieldName string) bool {
	if ks == nil {
		return false
	}
	for _, inst := range ks.Instances {
		if string(inst.ID) == fieldName {
			return true
		}
	}
	return false
}

// isFloatExpected checks if the expected expression is a floating point value.
func isFloatExpected(node expr.Node) bool {
	switch n := node.(type) {
	case expr.FloatNode:
		return true
	case expr.CastNode:
		return n.TypeName == "f4" || n.TypeName == "f8"
	case expr.UnaryNode:
		return isFloatExpected(n.Operand)
	default:
		return false
	}
}

// isByteArray checks if an array literal should be treated as a byte array.
// An array is a byte array if all items are simple integer literals in 0..255
// and there are no complex expressions (like 0 + 1).
func isByteArray(arr expr.ArrayNode) bool {
	for _, item := range arr.Items {
		in, ok := item.(expr.IntNode)
		if !ok {
			return false
		}
		if !in.Integer.IsInt64() {
			return false
		}
		v := in.Integer.Int64()
		if v < 0 || v > 255 {
			return false
		}
	}
	return true
}

// kstExceptionToGoType maps KS exception type names to Go types.
func kstExceptionToGoType(excType string) string {
	// Strip type parameters like <u1> from validation errors
	base := excType
	if before, _, ok := strings.Cut(excType, "<"); ok {
		base = before
	}

	switch base {
	case "EndOfStreamError":
		return "io.ErrUnexpectedEOF"
	case "ValidationNotEqualError":
		return "kaitai.ValidationNotEqualError"
	case "ValidationLessThanError":
		return "kaitai.ValidationLessThanError"
	case "ValidationGreaterThanError":
		return "kaitai.ValidationGreaterThanError"
	case "ValidationNotAnyOfError":
		return "kaitai.ValidationNotAnyOfError"
	case "ValidationExprError":
		return "kaitai.ValidationExprError"
	case "UndecidedEndiannessError":
		return "kaitai.UndecidedEndiannessError"
	default:
		return "kaitai." + base
	}
}
