// Code generated by "stringer -type=BitEndianKind"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnspecifiedBitOrder-0]
	_ = x[BigBitEndian-1]
	_ = x[LittleBitEndian-2]
}

const _BitEndianKind_name = "UnspecifiedBitOrderBigBitEndianLittleBitEndian"

var _BitEndianKind_index = [...]uint8{0, 19, 31, 46}

func (i BitEndianKind) String() string {
	if i < 0 || i >= BitEndianKind(len(_BitEndianKind_index)-1) {
		return "BitEndianKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BitEndianKind_name[_BitEndianKind_index[i]:_BitEndianKind_index[i+1]]
}
