// Code generated by "stringer -type=EndianKind"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnspecifiedOrder-0]
	_ = x[BigEndian-1]
	_ = x[LittleEndian-2]
	_ = x[SwitchEndian-3]
}

const _EndianKind_name = "UnspecifiedOrderBigEndianLittleEndianSwitchEndian"

var _EndianKind_index = [...]uint8{0, 16, 25, 37, 49}

func (i EndianKind) String() string {
	if i < 0 || i >= EndianKind(len(_EndianKind_index)-1) {
		return "EndianKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EndianKind_name[_EndianKind_index[i]:_EndianKind_index[i+1]]
}
