package c

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/jchv/zanbato/kaitai"
	"github.com/jchv/zanbato/kaitai/expr"
	"github.com/jchv/zanbato/kaitai/expr/engine"
	"github.com/jchv/zanbato/kaitai/kst"
	"github.com/jchv/zanbato/kaitai/types"
)

var _ = types.F4

type KSTEmitter struct {
	srcDir          string
	ResolvedStructs map[string]*kaitai.Struct
}

// NewKSTEmitter creates a C KST emitter.
func NewKSTEmitter(srcDir string) *KSTEmitter {
	return &KSTEmitter{srcDir: srcDir}
}

// Emit returns the generated filename and its contents.
func (e *KSTEmitter) Emit(spec *kst.TestSpec, ks *kaitai.Struct, ce *Emitter) (string, []byte) {
	g := &kstGen{
		emitter:    e,
		ce:         ce,
		spec:       spec,
		rootStruct: ks,
	}
	return spec.ID + "_test.c", g.generate()
}

type kstGen struct {
	emitter    *KSTEmitter
	ce         *Emitter
	spec       *kst.TestSpec
	rootStruct *kaitai.Struct
	out        bytes.Buffer
	indent     int
}

func (g *kstGen) writeln(format string, args ...any) {
	g.out.WriteString(strings.Repeat(indentStr, g.indent))
	fmt.Fprintf(&g.out, format, args...)
	g.out.WriteByte('\n')
}

func (g *kstGen) blank() { g.out.WriteByte('\n') }

func (g *kstGen) generate() []byte {
	typeName := g.ce.typeName(g.rootStruct.ID)
	dataPath := strings.ReplaceAll(g.emitter.srcDir+"/"+g.spec.Data, `\`, `\\`)
	dataPath = strings.ReplaceAll(dataPath, `"`, `\"`)

	g.writeln("/* Generated by Zanbato. Do not edit! */")
	g.writeln("#include <stdio.h>")
	g.writeln("#include <string.h>")
	g.writeln("#include <stdlib.h>")
	g.writeln("#include \"%s.h\"", strings.ToLower(string(g.rootStruct.ID)))
	g.blank()
	g.writeln("static int _failed = 0;")
	g.writeln("static int _checks = 0;")
	g.writeln("static int _skipped = 0;")
	g.blank()

	g.out.WriteString("#define CHECK(cond, msg) do { _checks++; if (!(cond)) { _failed++; fprintf(stderr, \"FAIL: %s\\n\", msg); } } while (0)\n")
	g.out.WriteString("#define SKIP(msg) do { _skipped++; fprintf(stderr, \"SKIP: %s\\n\", msg); } while (0)\n")
	g.blank()

	g.writeln("int main(void) {")
	g.indent++
	g.writeln("zb_arena_t arena; zb_arena_init(&arena);")
	g.writeln("zb_stream_t stream;")
	g.writeln("if (zb_stream_open(&stream, \"%s\") != ZB_OK) {", dataPath)
	g.indent++
	g.out.WriteString(strings.Repeat(indentStr, g.indent))
	g.out.WriteString("fprintf(stderr, \"open failed: " + escapeForC(dataPath) + "\\n\");\n")
	g.writeln("return 1;")
	g.indent--
	g.writeln("}")
	g.writeln("%s_t root;", typeName)
	g.writeln("int _err = %s_read(&root, &stream, &arena, &root, &root);", typeName)

	if g.spec.Exception != nil {
		g.writeln("if (_err == ZB_OK) { fprintf(stderr, \"expected parse error\\n\"); return 1; }")
		g.writeln("(void)_err;")
	} else if g.rootStruct != nil && g.rootStruct.Meta.Debug {
		g.writeln("(void)_err;")
	} else {
		g.writeln("if (_err != ZB_OK) { fprintf(stderr, \"parse failed: %%d\\n\", _err); return 1; }")
	}

	root := engine.NewStructValueSymbol(engine.NewStructSymbol(g.rootStruct, nil), nil)
	g.ce.context.AddGlobalType(string(g.rootStruct.ID), root)
	g.ce.context.AddModuleType(string(g.rootStruct.ID), root)
	g.ce.RegisterKnownStructs(g.emitter.ResolvedStructs)
	defer g.ce.enterModuleLocal(root)()
	defer g.ce.enterStruct(root, typeName)()
	if g.ce.file == nil {
		defer g.ce.pushFileScope(typeName)()
	}

	for i, a := range g.spec.Asserts {
		g.emitAssert(i, a, "root")
	}

	g.writeln("/* roundtrip check */")
	if g.spec.Exception != nil {
		g.writeln("/* skip roundtrip for top-level exception specs */")
		g.writeln("zb_arena_destroy(&arena);")
		g.writeln("if (_skipped) printf(\"SKIPPED: %%d\\n\", _skipped);")
		g.writeln("if (_failed) { fprintf(stderr, \"FAILED: %%d/%%d\\n\", _failed, _checks); return 1; }")
		g.writeln("printf(\"OK: %%d checks\\n\", _checks);")
		g.writeln("return 0;")
		g.indent--
		g.writeln("}")
		return g.out.Bytes()
	}
	if g.rootStruct != nil && g.rootStruct.Meta.Debug {
		g.writeln("if (_err != ZB_OK) {")
		g.indent++
		g.writeln("zb_arena_destroy(&arena);")
		g.writeln("if (_skipped) printf(\"SKIPPED: %%d\\n\", _skipped);")
		g.writeln("if (_failed) { fprintf(stderr, \"FAILED: %%d/%%d\\n\", _failed, _checks); return 1; }")
		g.writeln("printf(\"OK: %%d checks\\n\", _checks);")
		g.writeln("return 0;")
		g.indent--
		g.writeln("}")
	}
	g.writeln("size_t _read_pos = zb_stream_pos(&stream);")
	g.writeln("if (stream.bits_left > 0 && _read_pos > 0) _read_pos--;")
	g.writeln("zb_writer_t _w; zb_writer_init(&_w, &arena);")
	g.writeln("int _re = %s_write(&root, &_w);", typeName)
	g.writeln("if (_re == ZB_OK) {")
	g.indent++
	g.writeln("zb_bytes_t _ob = zb_writer_finalize(&_w);")
	g.writeln("size_t _cmp = _ob.len < _read_pos ? _ob.len : _read_pos;")
	g.writeln("uint8_t *_inbuf = (uint8_t *)zb_arena_alloc(&arena, _read_pos ? _read_pos : 1);")
	g.writeln("(void)zb_stream_seek(&stream, 0);")
	g.writeln("(void)zb_stream_read_raw(&stream, _inbuf, _read_pos);")
	g.writeln("if (_read_pos == 0 && _ob.len == 0) {")
	g.indent++
	g.writeln("printf(\"roundtrip OK (0 bytes)\\n\");")
	g.indent--
	g.writeln("} else if (_ob.len < _read_pos || memcmp(_ob.data, _inbuf, _cmp) != 0) {")
	g.indent++
	g.writeln("fprintf(stderr, \"roundtrip mismatch: read=%%zu wrote=%%zu\\n\", _read_pos, _ob.len);")
	g.indent--
	g.writeln("} else {")
	g.indent++
	g.writeln("printf(\"roundtrip OK (%%zu bytes)\\n\", _read_pos);")
	g.indent--
	g.writeln("}")
	g.indent--
	g.writeln("}")

	g.writeln("zb_arena_destroy(&arena);")
	g.writeln("if (_skipped) printf(\"SKIPPED: %%d\\n\", _skipped);")
	g.writeln("if (_failed) { fprintf(stderr, \"FAILED: %%d/%%d\\n\", _failed, _checks); return 1; }")
	g.writeln("printf(\"OK: %%d checks\\n\", _checks);")
	g.writeln("return 0;")
	g.indent--
	g.writeln("}")

	return g.out.Bytes()
}

func (g *kstGen) emitAssert(idx int, a kst.TestAssert, rootVar string) {
	if te, ok := a.(kst.TestException); ok {
		g.emitExceptionAssert(idx, te, rootVar)
		return
	}
	te, ok := a.(kst.TestEquals)
	if !ok {
		g.writeln(`SKIP("assert #%d: non-equals assert kind %T not implemented");`, idx, a)
		return
	}
	if strings.TrimSpace(te.Expected) == "null" {
		g.emitNullAssert(idx, te, rootVar)
		return
	}
	actualExpr, err := expr.ParseExpr(te.Actual)
	if err != nil {
		g.writeln(`SKIP("assert #%d: actual parse error: %s");`, idx, escapeForC(err.Error()))
		return
	}
	expectedExpr, err := expr.ParseExpr(te.Expected)
	if err != nil {
		g.writeln(`SKIP("assert #%d: expected parse error: %s");`, idx, escapeForC(err.Error()))
		return
	}

	defer g.ce.saveExprMode()()
	g.ce.mode.thisPointerName = "(&" + rootVar + ")"
	actualC, expectedC, prep := g.captureExprPrep2(actualExpr, expectedExpr)
	if prep != "" {
		g.out.WriteString(prep)
	}

	if arrLit, ok := expectedExpr.Root.(expr.ArrayNode); ok {
		if engine.ResultTypeOfNode(g.ce.context, actualExpr.Root).IsArrayResult() {
			elem := g.ce.arrayElemCTypeOfNode(actualExpr.Root)
			if elem == "" {
				elem = "int64_t"
			}
			g.emitArrayLiteralCheck(idx, te, actualC, arrLit, elem)
			return
		}
	}

	if g.ce.isNodeByteArray(actualExpr.Root) && g.ce.isNodeByteArray(expectedExpr.Root) {
		g.writeln("CHECK(zb_bytes_equal(%s, %s), \"assert #%d: %s == %s\");",
			actualC, expectedC, idx, escapeForC(te.Actual), escapeForC(te.Expected))
		return
	}
	if isFloatExpr(actualExpr.Root) || isFloatExpr(expectedExpr.Root) || g.actualIsFloat(actualExpr.Root) {
		g.writeln("{ double _a = (double)(%s); double _b = (double)(%s); double _d = _a - _b; if (_d < 0) _d = -_d; double _abs_b = _b < 0 ? -_b : _b; double _tol = _abs_b > 1.0 ? _abs_b * 1e-4 : 1e-4; CHECK(_d <= _tol || (_a == _b), \"assert #%d: %s == %s\"); }",
			actualC, expectedC, idx, escapeForC(te.Actual), escapeForC(te.Expected))
		return
	}
	g.writeln("CHECK(((%s) == (%s)), \"assert #%d: %s == %s\");",
		actualC, expectedC, idx, escapeForC(te.Actual), escapeForC(te.Expected))
}

func (g *kstGen) emitArrayLiteralCheck(idx int, te kst.TestEquals, actualC string, lit expr.ArrayNode, elem string) {
	g.writeln("/* array literal check: assert #%d */", idx)
	g.writeln("{")
	g.indent++
	arrType := g.ce.arrayTagFor(elem)
	g.writeln("%s _arr = (%s);", arrType, actualC)
	g.writeln("CHECK(_arr.len == %d, \"assert #%d: %s == %s (length mismatch)\");",
		len(lit.Items), idx, escapeForC(te.Actual), escapeForC(te.Expected))
	for i, item := range lit.Items {
		itemC, prep := g.captureExprPrep(func() string { return g.ce.exprNode(item) })
		if prep != "" {
			g.out.WriteString(prep)
		}
		itemIsBytes := g.ce.isNodeByteArray(item)
		if itemIsBytes {
			g.writeln("if (%d < _arr.len) CHECK(zb_bytes_equal(_arr.data[%d], %s), \"assert #%d: element %d\");",
				i, i, itemC, idx, i)
		} else {
			g.writeln("if (%d < _arr.len) CHECK(_arr.data[%d] == (%s), \"assert #%d: element %d\");",
				i, i, itemC, idx, i)
		}
	}
	g.indent--
	g.writeln("}")
}

func (g *kstGen) captureExprPrep(f func() string) (string, string) {
	prev := g.ce.file.source
	prep := &buf{pfx: strings.Repeat(indentStr, g.indent)}
	g.ce.file.source = prep
	defer func() { g.ce.file.source = prev }()
	result := f()
	return result, prep.String()
}

func (g *kstGen) captureExprPrep2(a, b *expr.Expr) (string, string, string) {
	prev := g.ce.file.source
	prep := &buf{pfx: strings.Repeat(indentStr, g.indent)}
	g.ce.file.source = prep
	defer func() { g.ce.file.source = prev }()
	aC := g.ce.expr(a)
	bC := g.ce.expr(b)
	return aC, bC, prep.String()
}

func escapeForC(s string) string {
	out := strings.Builder{}
	for _, r := range s {
		switch r {
		case '"', '\\':
			out.WriteByte('\\')
			out.WriteRune(r)
		case '\n':
			out.WriteString("\\n")
		default:
			out.WriteRune(r)
		}
	}
	return out.String()
}

func isFloatExpr(n expr.Node) bool {
	switch t := n.(type) {
	case expr.FloatNode:
		return true
	case expr.BinaryNode:
		return isFloatExpr(t.A) || isFloatExpr(t.B)
	case expr.UnaryNode:
		return isFloatExpr(t.Operand)
	}
	return false
}

func (g *kstGen) actualIsFloat(n expr.Node) (out bool) {
	defer func() { _ = recover() }()
	r := engine.ResultTypeOfNode(g.ce.context, n)
	if r == nil {
		return false
	}
	if r.Kind == engine.InstanceKind && r.Instance != nil && r.Instance.Value != nil {
		if g.ce.inferValueType(r.Instance.Value) == "double" {
			return true
		}
	}
	if vt, ok := r.ValueType(); ok && vt.Type.TypeRef != nil {
		k := vt.Type.TypeRef.Kind
		if k == types.F4 || k == types.F4le || k == types.F4be ||
			k == types.F8 || k == types.F8le || k == types.F8be ||
			k == types.UntypedFloat {
			return true
		}
	}
	if r.Kind == engine.FloatKind {
		return true
	}
	return false
}

func (g *kstGen) emitNullAssert(idx int, te kst.TestEquals, rootVar string) {
	actualExpr, err := expr.ParseExpr(te.Actual)
	if err != nil {
		g.writeln(`SKIP("assert #%d: actual parse error: %s");`, idx, escapeForC(err.Error()))
		return
	}
	defer g.ce.saveExprMode()()
	g.ce.mode.thisPointerName = "(&" + rootVar + ")"

	if op, prop, ok := nullableValueInstancePath(g.ce, actualExpr.Root); ok {
		g.writeln("{")
		g.indent++
		opC, prep := g.captureExprPrep(func() string { return g.ce.exprNode(op) })
		if prep != "" {
			g.out.WriteString(prep)
		}
		structName := g.ce.structOfNode(op)
		g.writeln("(void)%s_get_%s(%s);", structName, prop, opC)
		g.writeln(`CHECK(((%s)->_n_%s != 0), "assert #%d: %s == null");`,
			opC, prop, idx, escapeForC(te.Actual))
		g.indent--
		g.writeln("}")
		return
	}

	actualC, prep := g.captureExprPrep(func() string { return g.ce.expr(actualExpr) })
	if prep != "" {
		g.out.WriteString(prep)
	}
	g.writeln(`CHECK(((%s) == NULL), "assert #%d: %s == null");`,
		actualC, idx, escapeForC(te.Actual))
}

func nullableValueInstancePath(ce *Emitter, n expr.Node) (expr.Node, string, bool) {
	member, ok := n.(expr.MemberNode)
	if !ok {
		return nil, "", false
	}
	structName := ce.structOfNode(member.Operand)
	if structName == "" {
		return nil, "", false
	}
	res := engine.ResultTypeOfNode(ce.context, member.Operand)
	if res == nil {
		return nil, "", false
	}
	if res.Kind != engine.StructKind && res.Kind != engine.StructRootKind && res.Kind != engine.StructParentKind {
		return nil, "", false
	}
	if res.Struct == nil || res.Struct.Type == nil {
		return nil, "", false
	}
	for _, inst := range res.Struct.Type.Instances {
		if string(inst.ID) == member.Property && inst.Value != nil && inst.If != nil {
			if isScalarType(ce.inferValueType(inst.Value)) {
				return member.Operand, ce.fieldName(inst.ID), true
			}
		}
	}
	return nil, "", false
}

func (g *kstGen) emitExceptionAssert(idx int, te kst.TestException, rootVar string) {
	parsed, err := expr.ParseExpr(te.Actual)
	if err != nil {
		g.writeln(`SKIP("assert #%d exception: parse error: %s");`, idx, escapeForC(err.Error()))
		return
	}
	ident, ok := parsed.Root.(expr.IdentNode)
	if !ok {
		g.writeln(`SKIP("assert #%d exception: only top-level instance asserts supported (%s)");`,
			idx, escapeForC(te.Actual))
		return
	}
	var inst *kaitai.Attr
	for _, in := range g.rootStruct.Instances {
		if string(in.ID) == ident.Identifier {
			inst = in
			break
		}
	}
	if inst == nil {
		g.writeln(`SKIP("assert #%d exception: %s is not an instance",`,
			idx, escapeForC(te.Actual))
		return
	}
	typeName := g.ce.typeName(g.rootStruct.ID)
	fieldName := g.ce.fieldName(inst.ID)
	g.writeln("{")
	g.indent++
	g.writeln("%s._inst_err = 0;", rootVar)
	g.writeln("(void)%s_get_%s(&%s);", typeName, fieldName, rootVar)
	g.writeln(`CHECK(%s._inst_err != 0, "assert #%d: %s should raise");`,
		rootVar, idx, escapeForC(te.Actual))
	g.indent--
	g.writeln("}")
}
