name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - uses: NixOS/nix-installer-action@main

      - name: Run Flake Checks
        run: nix flake check
        if: success() || failure()

      - name: Build
        run: nix build .
        if: success() || failure()

      - name: Run Go tests
        run: nix develop --command go test ./...
        if: success() || failure()
