name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "45 0 * * *"
jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
      - name: Run Flake Checks
        run: nix flake check
        if: success() || failure()
      - name: Build
        run: nix build .
        if: success() || failure()
